#!/usr/bin/env bash
# scripts/generate-third-party-licenses.sh
#
# Generates THIRD_PARTY_LICENSES.md from the workspace's Cargo dependency tree.
#
# Requires: cargo-license  (cargo install cargo-license)
#           cargo          (standard Rust toolchain)
#
# Usage:
#   bash scripts/generate-third-party-licenses.sh           # writes THIRD_PARTY_LICENSES.md
#   bash scripts/generate-third-party-licenses.sh --check   # exit 1 if file is out of date

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

OUTPUT="THIRD_PARTY_LICENSES.md"
CHECK_MODE=false

for arg in "$@"; do
  [[ "$arg" == "--check" ]] && CHECK_MODE=true
done

if ! command -v cargo >/dev/null 2>&1; then
  echo "✗ cargo is required to generate license metadata. Install Rust toolchain first."
  echo "  See: https://www.rust-lang.org/tools/install"
  exit 1
fi

if ! command -v cargo-license >/dev/null 2>&1; then
  echo "→ Installing cargo-license..."
  cargo install --locked cargo-license
fi

TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

{
  cat <<'HEADER'
# Third-Party Licenses

This project depends on a number of open-source libraries.
Their names, versions, authors, and license identifiers are listed below.

> This file is auto-generated by `scripts/generate-third-party-licenses.sh`.
> Run `make third-party-licenses` to regenerate after updating `Cargo.toml`.
> Run `make check-third-party-licenses` to verify this file in CI/local checks.

| Crate | Version | License | Authors |
|-------|---------|---------|---------|
HEADER

  K8S_OPENAPI_ENABLED_VERSION=1.30 cargo license \
    --features "rest-api,metrics,admission-webhook,k8s-v1-30" \
    --avoid-build-deps \
    --avoid-dev-deps \
    --tsv 2>/dev/null \
    | tail -n +2 \
    | sort -f \
    | awk -F'\t' '{
        name=$1; version=$2; authors=$3; license=$5;
        gsub(/\|/, "\\|", name);
        gsub(/\|/, "\\|", authors);
        gsub(/\|/, "\\|", license);
        if (license == "") license = "(see crate)";
        printf "| %s | %s | %s | %s |\n", name, version, license, authors
      }'

} > "$TMPFILE"

if $CHECK_MODE; then
  if diff -q "$OUTPUT" "$TMPFILE" >/dev/null 2>&1; then
    echo "✓ $OUTPUT is up to date"
  else
    echo "✗ $OUTPUT is out of date. Run: make third-party-licenses"
    diff "$OUTPUT" "$TMPFILE" || true
    exit 1
  fi
else
  cp "$TMPFILE" "$OUTPUT"
  echo "✓ Generated $OUTPUT"
fi
